### ISSUE TITLE
Loss始终为Nan

### ISSUE THREAD

**Issue by sanyu6** [dgliu/KDD22_UEG#1]
你好我现在再跑这篇论文的代码, 使用 Readme中提供的命令，可是训练时loss始终为Nan。我不明白这其中是哪里出错了？

**Comment by dgliu** [comment]
你好，

在后期的业务落地中，我们也发现在一些与我们实验环境不同的Tensorflow版本上运行UEG会在训练过程中经常出现NaN值。

因此，我们建议您在和我们相同的实验环境中运行UEG（Tensorflow 1.15.x），在多个不同服务器上的测试都是正常的。

**Comment by sanyu6** [comment]
我这边使用的机器是V100 + tf1.15。 其结果还是Nan

**Comment by dgliu** [comment]
你好，再次和您确认一下，您的运行环境是python==3.6.9，tensorflow==1.15.3，后者是NVIDIA提供的版本？

如果是的话，能否提供更详细的环境描述，我们将尽可能在相同环境上进行测试。

我们先前在不同的v100和a100上都测试正常，以下是我们详细的环境描述：

absl-py                       0.10.0
alembic                       1.7.7
astor                         0.8.1
attrs                         20.2.0
audioread                     2.1.8
autopage                      0.5.0
backcall                      0.2.0
bleach                        3.1.5
certifi                       2020.6.20
cffi                          1.14.2
chardet                       3.0.4
click                         8.0.4
cliff                         3.10.1
cloudpickle                   1.6.0
cmaes                         0.8.2
cmd2                          2.4.1
colorama                      0.4.4
colorlog                      6.6.0
contextlib2                   0.6.0.post1
cupy                          8.0.0rc1
cycler                        0.10.0
Cython                        0.29.21
dataclasses                   0.8
decorator                     4.4.2
defusedxml                    0.6.0
DLLogger                      0.1.0        /workspace/src/dllogger
entrypoints                   0.3
fastrlock                     0.5
filelock                      3.4.1
future                        0.18.2
gast                          0.2.2
google-pasta                  0.2.0
googledrivedownloader         0.4
graphsurgeon                  0.4.5
greenlet                      1.1.2
grpcio                        1.32.0
h5py                          2.10.0
horovod                       0.19.2
html2text                     2020.1.16
huggingface-hub               0.4.0
idna                          2.10
importlib-metadata            1.7.0
importlib-resources           5.4.0
iniconfig                     1.0.1
ipykernel                     5.3.4
ipython                       7.16.1
ipython-genutils              0.2.0
jedi                          0.17.2
jieba                         0.42.1
Jinja2                        2.11.2
joblib                        0.14.0
json5                         0.9.5
jsonpatch                     1.28
jsonpointer                   2.0
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.6.3
jupyter-tensorboard           0.2.0
jupyterlab                    1.2.14
jupyterlab-server             1.2.0
jupytext                      1.6.0
Keras                         2.3.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.0.5
kiwisolver                    1.2.0
librosa                       0.7.1
llvmlite                      0.30.0
Mako                          1.1.6
Markdown                      3.2.2
markdown-it-py                0.5.4
MarkupSafe                    1.1.1
matplotlib                    3.1.1
mistune                       0.8.4
mock                          3.0.5
more-itertools                8.5.0
mpi4py                        3.0.3
munch                         2.5.0
mxboard                       0.1.0
nbconvert                     5.6.1
nbformat                      5.0.7
networkx                      2.5
nibabel                       3.1.1
nltk                          3.4.5
notebook                      6.0.3
numba                         0.46.0
numpy                         1.17.3
nvidia-dali-cuda110           0.25.1
nvidia-dali-tf-plugin-cuda110 0.25.1
nvtx-plugins                  0.1.8
onnx                          1.7.0
opencv-python                 4.5.1.48
opt-einsum                    3.3.0
optuna                        2.10.0
packaging                     21.3
pandas                        0.25.3
pandocfilters                 1.4.2
parso                         0.7.1
pbr                           5.8.1
pexpect                       4.7.0
pickleshare                   0.7.5
Pillow                        6.2.1
pip                           20.2.3
pluggy                        0.13.1
portalocker                   2.0.0
portpicker                    1.3.1
prettytable                   2.5.0
progressbar                   2.5
prometheus-client             0.8.0
prompt-toolkit                3.0.7
protobuf                      3.13.0
psutil                        5.7.0
ptyprocess                    0.6.0
py                            1.9.0
pycocotools                   2.0.0
pycparser                     2.20
Pygments                      2.6.1
pyparsing                     2.4.7
pyperclip                     1.8.2
pyrsistent                    0.16.0
pytest                        6.0.1
python-dateutil               2.8.1
python-speech-features        0.6
pytz                          2020.1
PyYAML                        5.3.1
pyzmq                         19.0.2
regex                         2022.4.24
requests                      2.24.0
resampy                       0.2.2
sacrebleu                     1.2.10
sacremoses                    0.0.49
scikit-learn                  0.23.2
scipy                         1.3.1
Send2Trash                    1.5.0
sentencepiece                 0.1.83
setuptools                    49.6.0
SimpleITK                     1.1.0
six                           1.13.0
SoundFile                     0.10.3.post1
SQLAlchemy                    1.4.35
stevedore                     3.5.0
tensorboard                   1.15.0+nv
tensorboard-plugin-dlprof     0.7
tensorboardX                  2.1
tensorflow                    1.15.3+nv
tensorflow-estimator          1.15.1
tensorrt                      7.1.3.4
termcolor                     1.1.0
terminado                     0.8.3
testpath                      0.4.4
tf2onnx                       1.6.3
threadpoolctl                 2.1.0
thulac                        0.2.1
tokenizers                    0.12.1
toml                          0.10.1
toposort                      1.5
torch                         1.9.1+cu111
torchaudio                    0.9.1
torchfile                     0.1.0
torchvision                   0.10.1+cu111
tornado                       6.0.4
tqdm                          4.48.2
traitlets                     4.3.3
transformers                  4.18.0
typing                        3.7.4.3
typing-extensions             3.7.4.3
uff                           0.6.9
urllib3                       1.25.10
visdom                        0.1.8.9
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.57.0
Werkzeug                      1.0.1
wheel                         0.35.1
wrapt                         1.12.1
zipp                          3.1.0

**Comment by dgliu** [comment]
> 我这边使用的机器是V100 + tf1.15。 其结果还是Nan

你好，请问你是否在和我们提供的相同环境上进行了测试，以及复现问题是否已经得到解决？
